### ISSUE TITLE
vue-marker not displaying on map and map not fully rendering

### ISSUE THREAD

**Issue by qualisign** [vue-leaflet/Vue2Leaflet#96] opened 2017-11-01 20:56 UTC
#### Steps to Reproduce

1. installed Vue2Leaflet via npm
2. created a component called `Simple `with the following contents (just copied the Simple.vue example and added the style import)
```

<template>
  <div class="simple">
    <div id="top_div" style="height: 100%">
      <v-map :zoom="zoom" :center="center" style="height: 1000px; width: 1000px">
        <v-tilelayer :url="url" :attribution="attribution"></v-tilelayer>
        <v-marker :lat-lng="marker"></v-marker>       
      </v-map>
    </div>
  </div>
</template>

<script>
 import Vue2Leaflet from 'vue2-leaflet';
 
export default {
  name: 'simple',
  components: {
    'v-map': Vue2Leaflet.Map,
    'v-tilelayer' :Vue2Leaflet.TileLayer,
    'v-marker': Vue2Leaflet.Marker
  },
  data () {
    return {
        zoom: 13,
        center: [47.413220, -1.219482],
        url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
        marker: L.latLng(47.413220, -1.219482),
    }
  }
}
</script>

<style>
 @import "~leaflet/dist/leaflet.css";
</style>
```

#### Expected Results
I expect to see the basic map with marker from the example jsfiddle.  

#### Actual Results
The map appears as a large gray box with a small section with rendered map tiles.  My problem looks identical to the one described in #81 , but I do include the leaflet css import.

![leaflet](https://user-images.githubusercontent.com/13368763/32297097-56751e10-bf4e-11e7-847e-3d97eb78ef7e.png)

What is strange is that when I resize the window, the map loads as it should, but the marker does not show up.  I see in the html that the marker is loaded, however: 
![leaflet2](https://user-images.githubusercontent.com/13368763/32297265-f04cbf98-bf4e-11e7-8f48-ab31a3abdcc4.png)

### Browsers Affected

- [x ] Chrome
- [x ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.2.0
- Vue: v2.5.2
- Vue2Leaflet: v0.0.55

**Comment by azurelogic** [comment] 2017-11-02 15:11
I've had some similar issues. The marker image issue I solved using info from these threads:
https://github.com/PaulLeCam/react-leaflet/issues/255
https://github.com/Leaflet/Leaflet/issues/4849
https://github.com/Leaflet/Leaflet/issues/4968

Basically, sounds like webpack is jacking up the embedded image URLs in the CSS. Throwing this at the top of your `main.js` may help:

```
import L from 'leaflet';
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')
});
```

I've gotten to the point that everything renders after the user resizes but I can't figure out why I'm getting grey space before that...

**Comment by azurelogic** [comment] 2017-11-02 15:32
I ended up with a hack that helped get everything to render correctly as far as the resize issue goes.

```
mounted() {
      setTimeout(function() { window.dispatchEvent(new Event('resize')) }, 250);
}
```

This works down to 200 ms. After that the hack fails. Seems to be some sort of race condition. I tested slower bandwidths and they work fine.

**Comment by qualisign** [comment] 2017-11-02 16:31
@azurelogic   

Both those suggestions worked, thanks for the help.

**Comment by KoRiGaN** [comment] 2017-11-07 11:35
Hi @qualisign,

The icon issue is well known. Leaflet and Webpack don't play well together. You can see the issue #28 and the pull request in Leaflet to fix this. 
@azurelogic  give the right way to fix this issue in the meantime.

The other issue is the map tiles not loading properly.
@azurelogic  seems right to force the view to be redrawn.
I can't reproduce and I would like to know how you reproduce it.
How do you set your map container size?

**Comment by azurelogic** [comment] 2017-11-07 18:02
The problem for me is that I'm using it along with Vuetity, which includes flexbox-based grid components. I have some tricks to size it as a square, but even before I added that on top I was having issues. I wish I had a simple example to illustrate.

**Comment by KoRiGaN** [comment] 2017-11-13 19:15
Never experienced any issue like this on my tests. 
It seems to me that this issue is a problem between Leaflet and flexbox based sizing. 
I should add this hack into a tips and tricks section in the Readme.

What do you think? 

Micka

**Comment by shaief** [comment] 2017-11-14 15:34
@KoRiGaN - i'm suffering from the same issue as @qualisign (see attached screenshot) but the solutions suggested by @azurelogic didn't solve my issue. Besides, when adding the leaflet.css import to app.vue, my screen is empty. When using developer tools to go over the elements i see that the tiles seem to be referenced correctly.
Any idea?
Thanks!


![screenshot-2017-11-14](https://user-images.githubusercontent.com/899702/32788505-083741f6-c962-11e7-9cee-806ddf4ffc4a.png)

**Comment by KoRiGaN** [comment] 2017-11-14 16:23
Hi @shaief,

What kind of setup are you using? 
Is Webpack or any bundling tool involved? 
Could you please share a repo reproducing that problem?

It looks more like a CSS Loading issue ... Hard to tell from a screenshot though.

Thanks,

Mickaël

**Comment by KoRiGaN** [comment] 2017-11-14 17:08
@shaief,
In your example, Leaflet's CSS is not imported and your map container has a height of 0px.
Fixing these issues make the map display correctly.

Mickaël

**Comment by shaief** [comment] 2017-11-14 17:12
@KoRiGaN - thanks!

**Comment by azurelogic** [comment] 2017-11-15 02:48
Can't hurt to suggest it. Like I said though, I'm using it inside of flexbox. On top of that, I'm binding the height of the map or its container to another property that's computed from the width of a column and stuff. Can't say that everything I'm doing is a good idea, but the whole site is pretty responsive. That's the difficulty with Leaflet to begin with though, it seems.

**Comment by gkatsanos** [comment] 2017-11-18 10:01
Same problem here. Vuetify / Flexbox + gray area showing up.

**Comment by KoRiGaN** [comment] 2017-12-14 17:24
I gave a try to Vuetify / Flexbox.

I started a Vue project added Vuetify and used [this layout](https://vuetifyjs.com/examples/layouts/baseline).
I added Vue2Leaflet and created a map component.
Added this map component in the main area of the baseline layout and leaflet CSS as a script tag in the index.html file.
Works fine.

The issue is that if the map container size change Leaflet doesn't know about it and doesn't load tiles to cover the new size of the container. 
It appends in my test when closing the left menu,  the maps get bigger a part of the map is now displayed on the right-hand side but no tile is displayed => grey area.

I'm not sure what your issue is as I can't really reproduce it but I think your map container is initialized with a small size(0px ?). The size is increased later but the map doesn't adapt like in my issue so you end up having a mostly grey area. 

**How to fix it** :
The tricky part is to detect when the size change, the only two options I found are: 
- Wait for [Resize Observer](https://wicg.github.io/ResizeObserver/) to be implemented in browsers and use it. At the moment no current version of browser implements it. It will work with Chrome 64.
 - Use a library called [CSS Element Queries](http://marcj.github.io/css-element-queries/) to detect changes using the ResizeSensor JS Class, debounce the events, and use Leaflet invalidateSize to force leaflet to adapt to the current size.   

The second seems to be the only viable choice.

What do you guys think?

**Comment by BrandonDevaleriola** [comment] 2018-03-06 09:25
If you type:  

`$('img.leaflet-marker-icon.leaflet-zoom-animated.leaflet-interactive').src `

you might get something like this :

> "data:image/png;base64,iVBORw0K[ ...................]UVORK5CYII=")marker-icon-2x.png"

 you will notice that the extra double quotes are screwing up the get request.
try removing this porting of the string and see if a marker appears.

> ")marker-icon-2x.png"

**Comment by BrandonDevaleriola** [comment] 2018-03-06 09:33
As for the issue with sizing issue in Vuetify: 
add a class on top of the  v-container  element : 


>  .i {
>    height: 100%;
>   margin: 0;
>    padding: 0;
>    width: 100%;
>    z-index: 0;
>  } 

then go into the vuetify.css and rip out all of the media queries for the .container class. I think its on lines 9301 to 9313.

**Comment by bboser** [comment] 2018-03-23 20:27
Apologies for the question, but where in the file system do I put the "leaflet.css" to include it with
     @import "~leaflet/dist/leaflet.css";

I've copied leaflet.css all over my disk, to no avail, and found no documentation of @import and were webpack looks for stuff.

**Comment by bboser** [comment] 2018-03-25 17:44
Many thanks, so simple ...

**Comment by Phyks** [comment] 2018-06-08 10:17
Hi,

I'm having similar issues as @azurelogic (Vuetify and flexbox rendering here, map is not rendered completely until a resize event).

I tried the https://github.com/KoRiGaN/Vue2Leaflet/issues/96#issuecomment-341459943 solution, but it does not work in my case as my component is mounted when the map object is created (but not necessarily rendered yet). Then, the timeout is not working and it seems super hacky to make it work.

I tried with the `load` event on the map, without any luck so far (the event does not seem to be triggered actually… :/).

Did anyone manage to find a working solution for this issue? Thanks!

**Comment by lordfuoco** [comment] 2018-07-25 08:48
@Phyks if you check the code coming from this pr: #200 you will see that I added an event called:  load
that you can listen to with `@load` on the l-map component.

You will need to use the code from my fork to have it for now

**Comment by chriscdn** [comment] 2018-08-07 15:43
@BrandonDevaleriola I'm having this double quote problem, which is causing the GET request to fail.  Is there a workaround or did I somehow miss it in your response?

**Comment by duebbert** [comment] 2018-08-24 14:54
I've had an issue with the grey area too (also using Vuetify). But I noticed that the issue went away if I change the zoom. So, a very dirty trick that I'm doing is that I programmatically zoom in and out again when the map loads. Then all seems to be fine and it's so fast that it's barely noticeable... not a nice workaround though I admit but none of the other suggestions here helped.

**Comment by nparley** [comment] 2018-10-11 19:53
For anyone having problems with vuetify this is the layout which is working for me:

```
<v-container class="pa-0" fluid fill-height>
        <v-layout>
            <v-flex x12>
                <l-map v-resize="onResize">
                </l-map>
            </v-flex>
        </v-layout>
</v-container>
```
And on resize I do:

```
onResize() {
    this.$refs.map.mapObject.invalidateSize();
}
```

**Comment by Alhakem** [comment] 2018-11-06 19:20
Hello guys, If you are facing such problem with vuetifyjs it's most probably that the map container is initialized with a small size.

To solve this problem you need to insure that you are loading the map whenever the container is taking the actual size.

For example, if you are using dialog as a container for the map, all what you have to do is using 'lazy' prop to insure that the content is rendered on mounted; in other words, the map must be rendered only if the dialog is activated 

```
<v-dialog v-model="dialog" lazy>
    <l-map
      :zoom="zoom"
      :center="center"
      :style="mapStyle"
      @update:center="centerUpdate"
      @update:zoom="zoomUpdate">
      <l-tile-layer
        :url="url"
        :attribution="attribution"/>
      <l-marker :lat-lng="marker">
      </l-marker>
    </l-map>
</v-dialog>
```

I hope this will help some one 😄

**Comment by tiangolo** [comment] 2019-01-06 09:38
It's working properly for me, after a couple configurations:

---

For the icons not showing up when using Webpack, there's now a plug-in to solve it at the Leaflet level: https://github.com/ghybs/leaflet-defaulticon-compatibility

My `main.ts` looks now like:

```TypeScript
import '@babel/polyfill';
// Import Component hooks before component definitions
import './component-hooks';
import Vue from 'vue';
import './plugins/vuetify';
import './plugins/vee-validate';
import App from './App.vue';
import router from './router';
import store from '@/store';
import './registerServiceWorker';
import 'vuetify/dist/vuetify.min.css';
import 'leaflet/dist/leaflet.css';
// Re-uses images from ~leaflet package
import 'leaflet-defaulticon-compatibility/dist/leaflet-defaulticon-compatibility.webpack.css';
import * as L from 'leaflet';
import 'leaflet-defaulticon-compatibility';

Vue.config.productionTip = false;

new Vue({
  router,
  store,
  render: (h) => h(App),
}).$mount('#app');
```

---

I'm using Vuetify. And I was having a gray area under the map, but I wasn't setting the `zoom` (my error). After setting a zoom higher than the default, the whole map region has rendered tiles properly.

The relevant section in my `.vue` file now looks like:

```Vue
<v-responsive :aspect-ratio="16/9">
  <LMap @click="onMapClick"
    :zoom="5"
  >
    <LTileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"></LTileLayer>
    <LMarker v-if="point" :lat-lng="point"></LMarker>
  </LMap>
</v-responsive>
```

And then in the script, as part of the component:

```TypeScript
  public onMapClick(e) {
    this.latitude = e.latlng.lat;
    this.longitude = e.latlng.lng;
  }

  get point() {
    if (this.latitude !== null && this.longitude !== null) {
      return {lat: this.latitude, lng: this.longitude};
    }
  }
```

I'm using TypeScript, but the plug-ins and configurations should work the same for normal JavaScript.

**Comment by r3j3c73d** [comment] 2019-01-09 16:22
Hi, I was done all stuff that guys said on top, but when I want to use lmap component in v-card of vuetify it disappears. What should i do to fix this? any suggestion?

**Comment by waleedshkt** [comment] 2019-02-16 23:48
I was experiencing the same issue of leaflet tile not fully loading on the map. 
After going through various solutions and hacks suggested above., I finally managed to solve the issue by calling: `this.$refs.map.mapObject.invalideSize()` inside `mounted` lifecycle hook.
Plus I set a hard-coded height and width of the map's parent container `<div>`.
And lastly, added the following code inside `main.js` file 

> (this step is though added in docs of vue2-leaflet when going through the installing section)

```import L from 'leaflet';
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')
});```

**Comment by waleedshkt** [comment] 2019-02-16 23:51
> FYI, I am using **iView UI Library**

I was experiencing the same issue of leaflet tile not fully loading on the map. 
After going through various solutions and hacks suggested above., I finally managed to solve the issue by calling: `this.$refs.map.mapObject.invalidateSize()` inside `mounted` lifecycle hook.
Plus I set a hard-coded height and width of the map's parent container `<div>`.
And lastly, added the following code inside `main.js` file 

> (this step is though added in docs of vue2-leaflet when going through the installing section)

```import L from 'leaflet';
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')
});```

**Comment by waleedshkt** [comment] 2019-02-16 23:52
> Btw, I am using **iView UI Library**

I was experiencing the same issue of leaflet tile not fully loading on the map. 
After going through various solutions and hacks suggested above., I finally managed to solve the issue by calling: `this.$refs.map.mapObject.invalideSize()` inside `mounted` lifecycle hook.
Plus I set a hard-coded height and width of the map's parent container `<div>`.
And lastly, added the following code inside `main.js` file 

> (this step is though added in docs of vue2-leaflet when going through the installing section)

```
import { L } from 'vue2-leaflet';
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')
});```

**Comment by waleedshkt** [comment] 2019-02-17 01:27
> FYI, I am using **iView UI Library**

I was experiencing the same issue of leaflet tile not fully loading on the map. 
After going through various solutions and hacks suggested above., I finally managed to solve the issue by calling: `this.$refs.map.mapObject.invalidateSize()` inside `mounted` lifecycle hook.
Plus I set a hard-coded height and width of the map's parent container `<div>`.
And lastly, added the following code inside `main.js` file 

> (this step is though added in docs of vue2-leaflet when going through the installing section)

```
import L from 'leaflet';
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')
});```

**Comment by kaboume** [comment] 2019-03-07 13:19
I have the same problem (Nuxt + Vuetify).
The solution of Alhakem works a little (add the "lazy" paramater) in the <v-bottom-sheet or v-dialog)
Ex 

`<v-bottom-sheet v-model="sheetMap" full-width lazy>`

This works at the first display of the v-bottom-sheet. But, after resizing the browser window and clicking on the button to show the v-bottom-sheet : only a part of the map is displayed..

In another page of the web site, I have a map in a tab panel (https://vuetifyjs.com/en/components/tabs) and I have the same issue : only a part ok the map is displayed.

IF you have an universal solution...

**Comment by Alhakem** [comment] 2019-03-07 17:36
Hi @kaboume ,

> This works at the first display of the v-bottom-sheet. But, after resizing the browser window and clicking on the button to show the v-bottom-sheet : only a part of the map is displayed.

As I mentioned above this issue happens because the changes in the container dimensions. However, I recommend you to overcome this issue by force Vue to re-render JUST the map component whenever the button is clicked to show the `v-bottom-sheet` 

Keep in mind that if you find yourself needing to force re-rendering any component, maybe you aren't doing something the right way.

> In another page of the web site, I have a map in a tab panel (https://vuetifyjs.com/en/components/tabs) and I have the same issue : only a part ok the map is displayed.

You can solve this the same way by using 'lazy' prop in `v-tab-item` tag

**Comment by kaboume** [comment] 2019-03-07 21:56
Hi @Alhakem ,
Thank you for the v-tab-item tag! I did not see that we could also use the "lazy" parameter in the v-tab!

Fot the sheet, the solution to rerender the Map works great!!! (I used the solution described at the bottom of this page : http://michaelnthiessen.com/force-re-render/).

I setted a key parameter on the map 

`<l-map :key="componentKey" ref="refMap" :zoom="10" :center="positionInitiale">`
        
and change the value of the componentKey after cliquing on the button to display the sheet 

```
forceRerender() {
      this.componentKey = this.componentKey + 1;
    },
```

```
watch: {
    sheetMap: function(val) {
      if (val == true) {
        this.$nextTick(() => {
          this.$refs.refMap2.forceRerender();
        });
      }
    }
  },
```

Big thanks to all!

**Comment by Alhakem** [comment] 2019-03-09 08:30
@kaboume well done 😊👍

**Comment by DonNicoJs** [comment] 2019-04-21 14:51
Is anyone in this thread up to write down in the docs some guidelines that are scattered here? It would be helpful for the next people with the same problems

**Comment by Alhakem** [comment] 2019-04-21 17:14
@DonNicoJs 

I can help with that

**Comment by DonNicoJs** [comment] 2019-04-22 14:26
@Alhakem Thanks! Waiting for a docs PR so :)

**Comment by GopherJ** [comment] 2019-06-01 05:25
![Screenshot from 2019-06-01 13-24-18](https://user-images.githubusercontent.com/33961674/58744139-a7ec5e00-8470-11e9-9314-eaddb07755cc.png)

this is absolutely crazy!~...............................

**Comment by GopherJ** [comment] 2019-06-02 10:36
![peekUXXZ2Z](https://user-images.githubusercontent.com/33961674/58759988-d9465600-8564-11e9-85da-591aed7b039d.gif)

**Comment by GopherJ** [comment] 2019-06-02 10:38
When I resize it restores, can someone help me?

**Comment by DonNicoJs** [comment] 2019-06-03 07:29
@GopherJ are you using vuetify ? have you read and tried the solution posted in this issue ?

**Comment by GopherJ** [comment] 2019-06-03 12:11
@DonNicoJs No, I'm not using vuetify. Why when I change tab it influences the map? By the way I'm using keep-alive for router

**Comment by kaboume** [comment] 2019-06-05 18:33
> Hi @Alhakem ,
> Thank you for the v-tab-item tag! I did not see that we could also use the "lazy" parameter in the v-tab!
> 
> Fot the sheet, the solution to rerender the Map works great!!! (I used the solution described at the bottom of this page : http://michaelnthiessen.com/force-re-render/).
> 
> I setted a key parameter on the map
> 
> `<l-map :key="componentKey" ref="refMap" :zoom="10" :center="positionInitiale">`
> 
> and change the value of the componentKey after cliquing on the button to display the sheet
> 
> ```
> forceRerender() {
>       this.componentKey = this.componentKey + 1;
>     },
> ```
> 
> ```
> watch: {
>     sheetMap: function(val) {
>       if (val == true) {
>         this.$nextTick(() => {
>           this.$refs.refMap2.forceRerender();
>         });
>       }
>     }
>   },
> ```
> 
> Big thanks to all!

Hi, 
There is a disadvantage to using the lazy property in the v-tab-item tag : SEO ! With a nuxt project in universal mode, the content of the v-tab-item is not created by the server side : when displaying the page soutce, the tab item is empty :( So, it's not the best solution when we have to optimize the SEO of the page.

**Comment by kaboume** [comment] 2019-06-28 11:33
Hi,
In order to work with SEO, I added a watch function when tab item is selected :


```
watch: {
    tabSelected: function(tabItem) {
      // Refresh the map of the tab
      this.$nextTick(() => {
        if (this.$refs.refCarteEtablissements) {
          this.$refs.refCarteEtablissements.map(ref => {
            ref.forceRerender();
          });
        }
      });
    }
  },
```

And I my CarteEtablissement component 


```
<l-map
        :zoom="13"
        :center="positionInitiale"
        :key="componentKey"
        style="z-index:1"
      >
....
</l-map>
```

```
 data() {
    return {
       ....
      componentKey: 0,
      ...
    };
  },
```

```
 methods: {
    forceRerender() {
      this.componentKey = this.componentKey + 1;
    },
}
```

And now the map displays correctly and when I show the source of the page, I see the text for the SEO.

**Comment by NewRanger** [comment] 2019-07-16 12:27
I am so sorry, is there any way to use local set of tiles? from assets folder for example. I can't figure out how to define {z}/{x}/{y} path to local tile set folder.

**Closed** 2020-01-08 12:58 UTC
Labels: Docs, help wanted, wontfix

**Comment by dstearle** [comment] 2020-02-27 22:00
Posting this here since it seems related. When viewing the examples for custom icons one vue2-leaflet's docs the re-sizable baseball icon that uses an l-icon tag strangley does not work in the provided code on the docs and jsfiddle (https://codesandbox.io/s/51sx6) although it does on the example in the docs itself (https://vue2-leaflet.netlify.com/examples/custom-icons.html). I found a fix for this by simply binding icon-url to a data property that uses require().

Another thing to note is that I am also using the solution posted by @azurelogic in the main.js.

**Comment by DonNicoJs** [comment] 2020-02-28 08:45
@dstearle Could you open a new issue to fix the docs? It would be greatly appreciated

**Comment by teleyinex** [comment] 2020-04-01 16:13
Quick update for those using vuetify 2.0. The lazy prop does not longer work, but v-lazy works:

```
v-lazy
  l-map
```

That will do the trick!

**Comment by iboates** [comment] 2021-02-24 12:36
I have a situation where my `<l-map>` component is inside a Vuetify stepper, and the problem is that it renders all of the `<v-stepper-content>` components at once, but then not the map. I'm not that experienced with Vue so maybe this is totally wrong, but it seems to be that the map is pre-initizalied at too-small a size and then when you step to the one with the map, it doesn't load properly and you get the grey square with the map tiles bunched up in the upper-left-hand corner.

I tried many solutions here but the only one I could get to work was to set a watcher on the variable controlling the stepper and use @azurelogic's `setTimeout`-based solution if the stepper variable is the one with the map on it, like this:

## Template

  ```
<v-stepper v-model="stepper">
      <v-stepper-items>
        <v-stepper-content step="1">
          <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn color="primary" @click.native="stepper = 2">Continue</v-btn>
          </v-card-actions>
        </v-stepper-content>
        <v-stepper-content step="2">
              <client-only>
                <l-map id="map" ref="map">
                  <l-tile-layer
                    :url="mapInitData.basemap.url"
                    :attribution="mapInitData.basemap.attribution"
                  />
                </l-map>
              </client-only>
        </v-stepper-content>
      </v-stepper-items>
    </v-stepper>
```

## Script

import ClientOnly from "vue-client-only";
import { LMap, LTileLayer, LGeoJson } from "vue2-leaflet";
import { Icon } from "leaflet";
delete Icon.Default.prototype._getIconUrl;
Icon.Default.mergeOptions({
  iconRetinaUrl: require("leaflet/dist/images/marker-icon-2x.png"),
  iconUrl: require("@/assets/marker-icon.png"),
  shadowUrl: require("leaflet/dist/images/marker-shadow.png")
});

export default {
  components: {
    LMap,
    LTileLayer,
    ClientOnly
  },
  data() {
    return {
      stepper: 1,
      mapInitData: {
        basemap: {
          attribution:
            '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
          url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        }
      },
      
  watch: {
    stepper: function (val) {
      if (val === 2) {
        this.reloadMap();
      }
    }
  },
  methods: {
    reloadMap: function() {
      console.log("reloading map");
      // this.$refs.map.mapObject.invalidateSize(); // Doesn't work!
      setTimeout(function() { window.dispatchEvent(new Event('resize')) }, 250);
    }
  }
};

**Comment by AlanGreyjoy** [comment] 2021-04-28 02:53
> Quick update for those using vuetify 2.0. The lazy prop does not longer work, but v-lazy works:
> 
> ```
> v-lazy
>   l-map
> ```
> 
> That will do the trick!

This guy right here! pin this somewhere!

**Comment by FuriosoJack** [comment] 2021-07-27 07:42
> Tengo una situación en la que mi `<l-map>`componente está dentro de un motor paso a paso de Vuetify, y el problema es que procesa todos los `<v-stepper-content>`componentes a la vez, pero no el mapa. No tengo tanta experiencia con Vue, así que tal vez esto esté totalmente mal, pero parece ser que el mapa está preiniciado en un tamaño demasiado pequeño y luego, cuando te acercas al que tiene el mapa, no se carga. correctamente y obtendrá el cuadrado gris con los mosaicos del mapa agrupados en la esquina superior izquierda.
> 
> Probé muchas soluciones aquí, pero la única que pude ponerme a trabajar fue establecer un observador en la variable que controla el paso a paso y usar la solución basada en @azurelogic`setTimeout` si la variable paso a paso es la que tiene el mapa, así:
> 
> ## Modelo
> ```
> <v-stepper v-model="stepper">
>     <v-stepper-items>
>       <v-stepper-content step="1">
>         <v-card-actions>
>           <v-spacer></v-spacer>
>           <v-btn color="primary" @click.native="stepper = 2">Continue</v-btn>
>         </v-card-actions>
>       </v-stepper-content>
>       <v-stepper-content step="2">
>             <client-only>
>               <l-map id="map" ref="map">
>                 <l-tile-layer
>                   :url="mapInitData.basemap.url"
>                   :attribution="mapInitData.basemap.attribution"
>                 />
>               </l-map>
>             </client-only>
>       </v-stepper-content>
>     </v-stepper-items>
>   </v-stepper>
> ```
> 
> ## Texto
> ```
> import ClientOnly from "vue-client-only";
> import { LMap, LTileLayer, LGeoJson } from "vue2-leaflet";
> import { Icon } from "leaflet";
> delete Icon.Default.prototype._getIconUrl;
> Icon.Default.mergeOptions({
>   iconRetinaUrl: require("leaflet/dist/images/marker-icon-2x.png"),
>   iconUrl: require("@/assets/marker-icon.png"),
>   shadowUrl: require("leaflet/dist/images/marker-shadow.png")
> });
> 
> export default {
>   components: {
>     LMap,
>     LTileLayer,
>     ClientOnly
>   },
>   data() {
>     return {
>       stepper: 1,
>       mapInitData: {
>         basemap: {
>           attribution:
>             '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
>           url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
>         }
>       },
>       
>   watch: {
>     stepper: function (val) {
>       if (val === 2) {
>         this.reloadMap();
>       }
>     }
>   },
>   methods: {
>     reloadMap: function() {
>       console.log("reloading map");
>       // this.$refs.map.mapObject.invalidateSize(); // Doesn't work!
>       setTimeout(function() { window.dispatchEvent(new Event('resize')) }, 250);
>     }
>   }
> };
> ```

Efectivamente this.$refs.map.mapObject.invalidateSize() no funciona y eso que los tengo en shadodom pero el setTimeOutSiFunciono

**Comment by pnavarretec01** [comment] 2022-01-26 16:04
> I ended up with a hack that helped get everything to render correctly as far as the resize issue goes.
> 
> ```
> mounted() {
>       setTimeout(function() { window.dispatchEvent(new Event('resize')) }, 250);
> }
> ```
> 
> This works down to 200 ms. After that the hack fails. Seems to be some sort of race condition. I tested slower bandwidths and they work fine.

This work for me!! thanks!!

**Comment by antoinegilles** [comment] 2022-07-27 07:36
> I ended up with a hack that helped get everything to render correctly as far as the resize issue goes.
> 
> ```
> mounted() {
>       setTimeout(function() { window.dispatchEvent(new Event('resize')) }, 250);
> }
> ```
> 
> This works down to 200 ms. After that the hack fails. Seems to be some sort of race condition. I tested slower bandwidths and they work fine.

thanks, it works, but I don't know if it's the cleanest solution :/
