### ISSUE TITLE
Visible for marker is not working (2.4.2)

### ISSUE THREAD

**Issue by pmochine** [vue-leaflet/Vue2Leaflet#512] opened 2020-01-14 05:46 UTC
### Description

Since updating vue2-leaftlet from 2.2.1 to 2.4.2, my markers are not functioning correctly! When I set visible to "false", the markers are still shown!

#### Live Demo

IMPORTANT: Your JSFiddler example (https://jsfiddle.net/Boumi/k04zpLx9/) is still using 1.0.1. I cannot find a CDN with ^2.0.0? I can't be the first one noticing it... SO you need to do this:

#### Steps to Reproduce
SO to see the bug, please Run code locally

```
# clone the repository
git clone https://github.com/KoRiGaN/Vue2Leaflet.git
cd Vue2Leaflet
# install dependencies and build vue2-leaflet
npm install
# create a symlink for vue2-leaflet
yarn link
cd examples
yarn install
# create a symbolic link for vue2-leaflet in node_modules/
yarn link vue2-leaflet
# serve with hot reload at localhost:8080
yarn run serve
```

NOW after that visit http://localhost:8080/ and click on **_"Some examples"_**. Click on the checkbox _**"Is Visible ?"**_ to see that the markers are not hiding! If you visit https://vue-leaflet.github.io/Vue2Leaflet/examples, it works because it still uses the old version.

![Ohne Titel](https://user-images.githubusercontent.com/25006691/72318099-4fec2a00-36d6-11ea-9451-87b2d06a4739.gif)

**Comment by JohnnyAW** [comment] 2020-01-14 12:45
Duplicate of #511

**Comment by rotsee** [comment] 2020-02-08 13:48
Is there a workaround for this, until it is fixed?

**Comment by pmochine** [comment] 2020-02-08 14:28
@rotsee downloading an older version. I didn't find any other solution

**Comment by DonNicoJs** [comment] 2020-02-09 12:05
@pmochine @rotsee @JohnnyAW I've addressed the issue and publish a new patch version.
I need absolutely to focus on: 
- docs
- ci
- tests

Apologies for the very slow update

**Closed by DonNicoJs** 2020-02-09 12:05 UTC
Labels: duplicate
